### ISSUE TITLE
Possible requirement for an asynchronous collection.get()

### ISSUE THREAD

**Issue by axit-joost** [Wizcorp/express-rested#41]
I'm working on a project that basically does this:

```js
const devices = require('../lib/resources').devices;
const prober = require('../lib/prober');

const device = devices.get('7fd590de-5726-436d-8c84-95e4738a9742');
prober.probeDevice(device);
```

When running this script in node, the device passed to probeDevice is still undefined.
when running these commands from the node REPL, it works fine.

**Comment by ronkorving** [comment]
Solved with you offline, not related to express-rested :) :+1:
