### ISSUE TITLE
Version mismatch on npm

### ISSUE THREAD

**Issue by axit-rasmus** [Wizcorp/express-rested#42]
The version on npm says 1.5.1 but it's not actually the same as on github.
Telling was the missing piece of documentation on errors (and the missing event emitter in the actual source).

**Comment by ronkorving** [comment]
I don't think there's a version mismatch, as the latest version on GitHub is also 1.5.1. I think what you're really saying is that the latest master branch has not been released and you would like to see a release. I shall make it so! :)

**Comment by ronkorving** [comment]
Released 1.6.0
