### ISSUE TITLE
Re-attach prototype

### ISSUE THREAD

**Issue by axit-rasmus** [Wizcorp/express-rested#43]
Since a `Collection<Foo>` keeps track of the prototype, it would be nice if it was automatically used for anything new. In a case where I iterate over a number of these resources I don't want to have to redo this every time, in every place I intend to use these methods.

I currently have code like this
```
for (const id of collection.getIds()) {
	let resource = collection.get(id);

	if (!(resource instanceof collection.Class)) {
		resource = Object.create(collection.Class.prototype, resource);
		collection.set(id, resource);
	}

	// safely use resource
}
```

**Comment by ronkorving** [comment]
That should already be the case. Could you file a failing test if that's broken?

**Comment by axit-rasmus** [comment]
Breakage was on my end, and I misread the collection source. Sigh
